{application,erpc,
    [{description,"ERPC Client  %VSN%"},
     {vsn,"%VSN%"},
     {modules,
         [erpc,erpc_client_appsup,erpc_connection,erpc_group_appsup,
          erpc_stream_recv]},
     {registered,[erpc]},
     {applications,[proc_reg]},
     {mod,{erpc_group_appsup,[]}},
     {env,[{groups,[{default_group,[{backends,[{"localhost",55555}]}]}]}]}]}.
